// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from './application';

import DropdownController from './dropdown_controller';
import LiveStreamController from './live_stream_controller';
import MobileMenuController from './mobile_menu_controller';
import TrackViewController from './track_view_controller';

application.register('dropdown', DropdownController);
application.register('live-stream', LiveStreamController);
application.register('mobile-menu', MobileMenuController);
application.register('track-view', TrackViewController);
