# frozen_string_literal: true

# == Schema Information
#
# Table name: download_tokens
#
#  id                 :bigint           not null, primary key
#  download_count     :integer          default(0), not null
#  expires_at         :datetime         not null
#  last_downloaded_at :datetime
#  max_downloads      :integer          default(5), not null
#  token              :string           not null
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  purchase_id        :bigint           not null
#
# Indexes
#
#  index_download_tokens_on_expires_at   (expires_at)
#  index_download_tokens_on_purchase_id  (purchase_id)
#  index_download_tokens_on_token        (token) UNIQUE
#
# Foreign Keys
#
#  fk_rails_...  (purchase_id => purchases.id)
#
FactoryBot.define do
  factory :download_token do
    association :purchase
    # Token and expires_at are auto-generated by the model callbacks

    trait :expired do
      expires_at { 1.hour.ago }
    end

    trait :exhausted do
      download_count { 5 }
      max_downloads { 5 }
    end

    trait :almost_exhausted do
      download_count { 4 }
      max_downloads { 5 }
    end

    trait :fresh do
      download_count { 0 }
      expires_at { 1.hour.from_now }
    end

    trait :used_once do
      download_count { 1 }
      last_downloaded_at { 30.minutes.ago }
    end

    trait :high_limit do
      max_downloads { 10 }
    end
  end
end
