# Overcommit configuration for Curated.www
# Git hooks for quality enforcement
# See: https://github.com/sds/overcommit

# Verify signature of the file to ensure it hasn't been tampered with
verify_signatures: true

PreCommit:
  ALL:
    problem_on_unmodified_line: warn
    required: false
    quiet: false

  RuboCop:
    enabled: true
    on_warn: fail
    command: ['bundle', 'exec', 'rubocop']
    flags: ['--format', 'emacs', '--force-exclusion', '--display-cop-names']
    problem_on_unmodified_line: warn

  ErbLint:
    enabled: true
    on_warn: fail
    command: ['bundle', 'exec', 'erb_lint']

  TrailingWhitespace:
    enabled: true
    exclude:
      - '**/db/structure.sql'
      - '**/vendor/**/*'

  MergeConflicts:
    enabled: true
    required: true

CommitMsg:
  ALL:
    required: false

  TextWidth:
    enabled: true
    max_subject_width: 72
    max_body_width: 80

  HardTabs:
    enabled: true

PrePush:
  ALL:
    required: false
    quiet: false

  Brakeman:
    enabled: true
    on_warn: warn
    command: ['bundle', 'exec', 'brakeman']
    flags: ['--quiet', '--no-pager', '--exit-on-warn', '-i', 'config/brakeman.ignore']

  RSpec:
    enabled: true
    on_warn: fail
    command: ['bundle', 'exec', 'rspec']
    flags: ['--format', 'progress', '--exclude-pattern', 'spec/system/**/*_spec.rb']
