version: 1
installed_agents:
  - cursor
  - claude
  - codex
  - gemini
  - copilot
  - opencode
last_generated: 2026-01-20T21:05:35.131Z
files:
  - path: .cursorrules
    sources: []
    hash: b6d9f737a759c032
  - path: CLAUDE.md
    sources: []
    hash: 0793562c7596d9aa
  - path: AGENTS.md
    sources: []
    hash: 2d776629ab6fb841
  - path: GEMINI.md
    sources: []
    hash: 436fb3572e4b01d6
  - path: .github/copilot-instructions.md
    sources: []
    hash: c3a15542ab9db1ae
  - path: OpenCode.md
    sources: []
    hash: f4cc457914ce31e8
  - path: .opencode.json
    sources: []
    hash: 49398b6361c6981c
